
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/checkinn
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - app-uploads:/app/uploads
    depends_on:
      - db
    networks:
      - checkinn-network

  db:
    image: mariadb:10.7
    container_name: checkinn-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=checkinn
      - MYSQL_USER=checkinn
      - MYSQL_PASSWORD=checkinn
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - checkinn-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  checkinn-network:
    driver: bridge

volumes:
  mariadb-data:
  app-uploads: